"""Phase 1: core travel data. Frozen schema, independent of application models."""

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002_core"
down_revision = "0001_postgis"
branch_labels = None
depends_on = None

visit_source = postgresql.ENUM(
    "MANUAL", "PHOTO", "BOOKING", "IMPORT", "GPS", "AI", name="visit_source", create_type=False
)


def upgrade() -> None:
    visit_source.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places",
        sa.Column("canonical_name", sa.String(length=300), nullable=False),
        sa.Column("local_name", sa.String(length=300), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("admin1", sa.String(length=200), nullable=True),
        sa.Column("admin2", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=200), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("osm_id", sa.String(length=100), nullable=True),
        sa.Column("google_place_id", sa.String(length=300), nullable=True),
        sa.Column("amap_id", sa.String(length=100), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_places")),
        sa.UniqueConstraint("amap_id", name=op.f("uq_places_amap_id")),
        sa.UniqueConstraint("google_place_id", name=op.f("uq_places_google_place_id")),
        sa.UniqueConstraint("osm_id", name=op.f("uq_places_osm_id")),
    )
    op.create_index(
        "idx_places_location", "places", ["location"], unique=False, postgresql_using="gist"
    )
    op.create_table(
        "users",
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("locale", sa.String(length=35), server_default="zh-CN", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "trips",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IDEA",
                "PLANNING",
                "BOOKED",
                "TRAVELING",
                "COMPLETED",
                "ARCHIVED",
                name="trip_status",
            ),
            server_default="IDEA",
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("visibility", sa.String(length=16), server_default="PRIVATE", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("visibility = 'PRIVATE'", name=op.f("ck_trips_private_visibility")),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_trips_date_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trips_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_trips_id")),
        sa.UniqueConstraint("user_id", "slug", name=op.f("uq_trips_user_id")),
    )
    op.create_index("ix_trips_user_start", "trips", ["user_id", "start_date"], unique=False)
    op.create_table(
        "trip_days",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_trip_days_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_days")),
        sa.UniqueConstraint("id", "trip_id", name=op.f("uq_trip_days_id")),
        sa.UniqueConstraint("trip_id", "date", name=op.f("uq_trip_days_trip_id")),
    )
    op.create_table(
        "activities",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("trip_day_id", sa.Uuid(), nullable=False),
        sa.Column("place_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "VISIT",
                "TRANSPORT",
                "FOOD",
                "HOTEL",
                "EVENT",
                "FREE_TIME",
                "OTHER",
                name="activity_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CANDIDATE", "PLANNED", "CONFIRMED", "COMPLETED", "SKIPPED", name="activity_status"
            ),
            server_default="PLANNED",
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source", visit_source, server_default="MANUAL", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_at IS NULL OR start_at IS NULL OR end_at >= start_at",
            name=op.f("ck_activities_time_range"),
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_activities_place_id_places"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trip_day_id", "trip_id"],
            ["trip_days.id", "trip_days.trip_id"],
            name="fk_activities_day_trip",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_activities_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index("ix_activities_trip", "activities", ["trip_id", "sort_order"], unique=False)
    op.create_table(
        "visits",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=True),
        sa.Column("trip_day_id", sa.Uuid(), nullable=True),
        sa.Column("place_id", sa.Uuid(), nullable=False),
        sa.Column("visited_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", visit_source, server_default="MANUAL", nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_visits_confidence_range"),
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= visited_at", name=op.f("ck_visits_time_range")
        ),
        sa.CheckConstraint(
            "trip_day_id IS NULL OR trip_id IS NOT NULL", name=op.f("ck_visits_day_requires_trip")
        ),
        sa.ForeignKeyConstraint(
            ["place_id"], ["places.id"], name=op.f("fk_visits_place_id_places"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["trip_day_id", "trip_id"],
            ["trip_days.id", "trip_days.trip_id"],
            name="fk_visits_day_trip",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id", "user_id"],
            ["trips.id", "trips.user_id"],
            name="fk_visits_trip_owner",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_visits_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visits")),
    )
    op.create_index("ix_visits_place", "visits", ["place_id"], unique=False)
    op.create_index("ix_visits_trip", "visits", ["trip_id"], unique=False)
    op.create_index("ix_visits_user_time", "visits", ["user_id", "visited_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ("visits", "activities", "trip_days", "trips", "users", "places"):
        op.drop_table(table)
    for name in ("activity_status", "activity_type", "visit_source", "trip_status"):
        postgresql.ENUM(name=name).drop(op.get_bind(), checkfirst=True)
